// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edjtqvwxmxusdejdrcki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkanRxdnd4bXh1c2RlamRyY2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjQyMDksImV4cCI6MjA2MDgwMDIwOX0.PxBQ2f2MEbZmPJ5rD4OJ3-7ULgqqhLo8HUWdHPy33Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);